export { default as AdminDashboardPage } from './pages/AdminDashboardPage/AdminDashboardPage';
export { default as ApplicationListPage } from './pages/ApplicationListPage/ApplicationListPage';
export { default as ApplicationDetailPage } from './pages/ApplicationDetailPage/ApplicationDetailPage';
export { default as AdminInspectionPage } from './pages/AdminInspectionPage/AdminInspectionPage';
export { default as AdminInspectionDetailPage } from './pages/AdminInspectionDetailPage/AdminInspectionDetailPage';
export { default as FranchiseeListPage } from './pages/FranchiseeListPage/FranchiseeListPage';
export { default as StoresPage } from './pages/StoresPage/StoresPage';
export { default as PurchaseOrderPage } from './pages/PurchaseOrderPage/PurchaseOrderPage';
export { default as AdminQuarterlyRevenuePage } from './pages/AdminQuarterlyRevenuePage/AdminQuarterlyRevenuePage';